### PR TITLE
cache aggressive illegal item search results

### PR DESCRIPTION
**Pull request by ultra64cmy**
When doing agro illegal item checks, cache the results in a per-player LRU. As long as players don't stray far from busy chunks (default: 1024 chunks) the agro check won't refire. This gracefully handles players who are traveling and stationary players by keeping the caches per player.

Should help #24

### CODE REVIEW

**Comment by gcurtiss** [comment]
is this tested using the repro case described in #24

**Comment by ultra64cmy** [comment]
No, I don't have a chunk like that and stopped making one after about 25 minutes and only 5% done. Can you worldedit out a chunk or help think of another way to automatically create an evil chunk?

**Comment by gcurtiss** [comment]
was able to reproduce with one chunk full of chests containing a shulker filled with stacks of slabs

you can clone a chest by ctrl+middle clicking the chest. this will give you a chest + nbt

make sure debug=false in the config or the server will crash

**Comment by gcurtiss** [comment]
watch tps as you move in/out of the chunk. with your design it should only dip once

**Comment by gcurtiss** [comment]
~20-30 dubs should work to observe a spike, scale as you need

**Comment by ultra64cmy** [comment]
Tested against a chunk with 36 dubs, tick time around 200 ms. Only observed the long tick when I flew far enough away to evict cache or flushed it on timer. See screenshot.

**Pull request merged**
